apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev-playground
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
  type: ClusterIP
