apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: dev-playground
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: ClusterIP  # Headless service for internal DNS resolution
